WITH hubspot_contacts as (
    SELECT * FROM {{ ref('stg_hubspot_contacts') }}
), rds_contacts as (
    SELECT * FROM {{ ref('stg_rds_customers') }}
), merged_contacts as(
    SELECT CONTACT_ID AS HUBSPOT_CONTACT_ID, NULL AS RDS_CONTACT_ID, FIRST_NAME, LAST_NAME, PHONE, 
    COMPANY_ID AS HUBSPOT_COMPANY_ID, NULL AS RDS_COMPANY_ID
    FROM hubspot_contacts UNION ALL
    SELECT NULL AS HUBSPOT_CONTACT_ID, CUSTOMER_ID as RDS_CONTACT_ID, FIRST_NAME, LAST_NAME, PHONE, 
    NULL AS HUBSPOT_COMPANY_ID, COMPANY_ID AS RDS_COMPANY_ID
    FROM rds_contacts  
), cleaned_contacts as (SELECT MAX(HUBSPOT_CONTACT_ID) AS HUBSPOT_CONTACT_ID, MAX(RDS_CONTACT_ID) AS RDS_CONTACT_ID, FIRST_NAME, LAST_NAME, 
    MAX(PHONE) as PHONE, MAX(HUBSPOT_COMPANY_ID) AS HUBSPOT_COMPANY_ID, MAX(RDS_COMPANY_ID) AS RDS_COMPANY_ID 
    FROM merged_contacts GROUP BY FIRST_NAME, LAST_NAME
)
SELECT {{ dbt_utils.surrogate_key(['first_name', 'last_name', 'phone']) }} as CONTACT_PK, HUBSPOT_CONTACT_ID, RDS_CONTACT_ID, 
FIRST_NAME, LAST_NAME, PHONE, HUBSPOT_COMPANY_ID, RDS_COMPANY_ID
FROM cleaned_contacts
